"""first alembic migration

Revision ID: 7b891f2bf045
Revises:
Create Date: 2025-05-22 11:05:17.252577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b891f2bf045"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone", sa.String(), nullable=True))


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
#     op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
#     op.create_unique_constraint(None, 'users', ['email'])
#     # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone")


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, "users", type_="unique")
#     op.drop_index(op.f("ix_users_id"), table_name="users")
#     op.drop_index(op.f("ix_todos_id"), table_name="todos")
#     # ### end Alembic commands ###
