"""add email vervifaction to User Model

Revision ID: 28435b99de97
Revises: b82f13269477
Create Date: 2025-08-05 09:57:42.548441

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28435b99de97"
down_revision: Union[str, None] = "b82f13269477"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "delivery_partner", sa.Column("email_verified", sa.Boolean(), nullable=True)
    )
    op.add_column("seller", sa.Column("email_verified", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seller", "email_verified")
    op.drop_column("delivery_partner", "email_verified")
    # ### end Alembic commands ###
