"""2nd try

Revision ID: 7ad39fd271b9
Revises: 41ab7d0073f0
Create Date: 2025-06-12 06:37:15.054231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "7ad39fd271b9"
down_revision: Union[str, None] = "41ab7d0073f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "seller",
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seller", "address")
    # ### end Alembic commands ###
