"""adding client contact info to Shipment model

Revision ID: b82f13269477
Revises: 29b29f45e020
Create Date: 2025-07-25 23:31:28.284119

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b82f13269477"
down_revision: Union[str, None] = "29b29f45e020"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shipment",
        sa.Column(
            "client_contact_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "shipment", sa.Column("client_contact_phone", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shipment", "client_contact_phone")
    op.drop_column("shipment", "client_contact_email")
    # ### end Alembic commands ###
